{% set name = "clean-text" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/clean-text-{{ version }}.tar.gz
  sha256: 648de7c65d474c65c36ec7d1f19e815c942d67bde2db4894d3930afb75da769e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
  run:
    - emoji
    - ftfy >=5.8,<6.0
    - python >={{ python_min }},<3.9

test:
  imports:
    - cleantext
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/clean-text/
  summary: Functions to preprocess and normalize text.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - FernandezMathieu
